# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('e', 'Em andamento'), ('c', 'Cancelado'), ('f', 'Finalizado'), ('a', 'Atrasado')], default='b', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, choices=[('b', 'Bacharel'), ('e', 'Educacao'), ('s', 'Saude'), ('l', 'Licenciatura')], default='b', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Escolha_questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha', models.CharField(blank=True, choices=[('1', 'Nulo'), ('2', 'Ruim'), ('3', 'Razoável'), ('4', 'Bom'), ('5', 'Muito bom')], default='3', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('b', 'Bacharel'), ('e', 'Educacao'), ('s', 'Saude'), ('l', 'Licenciatura')], default='b', max_length=1)),
                ('enunciado1', models.CharField(max_length=500)),
                ('enunciado2', models.CharField(max_length=500)),
                ('enunciado3', models.CharField(max_length=500)),
                ('enunciado4', models.CharField(max_length=500)),
                ('enunciado5', models.CharField(max_length=500)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.Avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha_questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.Escolha_questao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.Questao')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.Avaliacao')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=200)),
                ('data_ingresso', models.DateField(blank=True, null=True)),
                ('curso', models.ManyToManyField(to='questionario.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='resposta',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.Resultado'),
        ),
        migrations.AddField(
            model_name='escolha_questao',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.Questao'),
        ),
    ]
