# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='data_semestre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
